blueprints/qa.py
from flask import flash, Blueprint, redirect, url_for, render_template, request, g
from decorators import login_required
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from sqlalchemy import or_

bp = Blueprint("qa", __name__, url_prefix="/")


# 问答页就是首页
@bp.route("/")
def index():
    # questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("index.html", questions=questions)


# 发布问答
@bp.route("/question/public", methods=["GET", "POST"])
# 判断用户是否登录，如果没有登录则无法进入问答页面。并提醒用户登录
@login_required  # 将以下函数当作一个参数，传给修饰器。在修饰器中闭包的进行判断
def public_question():
    if request.method == "GET":
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误！")
            return redirect(url_for("qa.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html", question=question)


# 发布评论
# @bp.post("/answer/<int:question_id>")
@bp.route("/answer/<int:question_id>", methods=["GET","POST"])
# 判断用户是否登录，如果没有登录则无法进入问答页面。并提醒用户登录
@login_required
def answer(question_id):
    if not g.user:
        return redirect(url_for("user.login"))

    else:

        form = AnswerForm(request.form)
        if form.validate():
            content = form.content.data
            answer_model = AnswerModel(content=content, author=g.user, question_id=question_id)
            db.session.add(answer_model)
            db.session.commit()
            return redirect(url_for("qa.question_detail", question_id=question_id))
        else:
            flash("请输入评论后发布")
            return redirect(url_for("qa.question_detail", question_id=question_id))


@bp.route("/search")
def search():
    # url显示 /search？key=xxx
    key = request.args.get("key")  # 获取用户传输的参数,"key"为前端定义的搜索框的名称
    # filter_by 直接使用字段的名称
    # filter 使用模型.字段名称
    questions = QuestionModel.query.filter(
        # QuestionModel.title.contains(key) 标题包含关键字（key接收关键字）
        # 使用Model.Column.Contains(keyword)与filter结合来筛选指定的Column字段包含keyword的内容，由于我们的逻辑是或的关系，所以使用了一个从sqlalchemy中导出的or_函数。
        # or_(QuestionModel.title.contains(key), QuestionModel.content.contains(key))).order_by(db.text("-create_time"))
        or_(QuestionModel.title.contains(key), QuestionModel.content.contains(key))).order_by(QuestionModel.create_time.desc()).all()
    if questions:
        return render_template("index.html", questions=questions)
    else:
        return render_template("warn.html")

blueprints/user.py
from flask import flash, jsonify, Blueprint, render_template, request, redirect, url_for, session, g, current_app
from exts import mail, db, redis_store
from flask_mail import Message  # 导入邮箱信息
from models import EmailCaptchaModel, UserModel
# 导入字符串和随即库用于生成验证码
import string
import random
import datetime

from datetime import datetime
from .forms import RegisterForm, LoginForm, RepasswordForm, MessageForm
from werkzeug.security import generate_password_hash, check_password_hash

# 引入装饰器
from decorators import login_required

bp = Blueprint("user", __name__, url_prefix="/user")  # url_prefix :设置url前缀


# 注册
# GET: 客户端从服务器端获取数据
# POST：将客户端数据提交到服务器
@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template('register.html')  # 返回页面
    elif request.method == "POST":
        form = RegisterForm(request.form)  # 将request.form获取的数据给RegisterForm进行格式验证
        if form.validate():  # 如果验证串成功
            email = form.email.data
            username = form.username.data
            sex = request.form["sex"]
            print(email, username, sex)
            # md5 加密
            password = form.password.data
            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password, sex=sex)
            # try:
            db.session.add(user)
            db.session.commit()
            # flash(f"账号{email}已注册成功")
            return redirect(url_for('user.login'))
            # except:
            #     db.session.rollback()
            #     return redirect(url_for('user.register'))
        else:
            return redirect(url_for('user.register'))


# 登录
@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            form_check_label = request.form.get("form-check-label")
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                flash("邮箱未注册！")
                return redirect(url_for("user.login"))
            elif user and check_password_hash(user.password, password):
                # 使用session存放用户信息
                session["user_id"] = user.id
                if form_check_label:
                    """
                    permanent是“永久”的意思，
                    如果设置了此项为True，
                    意味着在permanent_session_lifetime过期时间内即使关闭浏览器，再次打开时session还有效
                    如果设置了此项为False，
                    即使在session的有效期内关闭浏览器，也会清空session，从而导致登录失效
                    还有就是，session.permanent只能在视图内设置，不能和过期时间一起设置
                    """
                    session.permanent = True
                    bp.permanent_session_lifetime = datetime.timedelta(days=10)
                # 登录成功，返回首页
                return redirect("/")
            else:
                flash("密码错误")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱格式错误或密码长度少于6")
            return redirect(url_for("user.login"))


# 退出登录
@bp.route("/logout")
def logout():
    # 清除session中的数据
    session.clear()
    return redirect(url_for("user.login"))


# 生成验证码并通过邮箱发送
@bp.route("/captcha", methods=["POST"])
def get_captcha():
    # POST传参  获取用户注册时输入的邮箱
    email = request.form.get('email')
    # 生成验证码
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters, 4))
    if email:  # 如果填入邮箱则进行以下处理
        # 实例化信息
        message = Message(
            subject='知了问答注册',  # 主题
            recipients=[email],  # 收件人,多人用';'间隔
            body=f'【知了问答】您的注册验证码是:{captcha},有效时间为两分钟。请确认该操作是本人执行。',  # 内容
            # html=None,  # 样式
            sender='1902206219@qq.com'  # 发送者
            # cc=None,
            # bcc=None,
            # attachments=None,
            # reply_to=None,
            # date=None,
            # charset=None,
            # extra_headers=None,
            # mail_options=None,
            # rcpt_options=None
        )
        # 发送邮箱
        mail.send(message)
        # 查询数据库是否存在该邮箱和验证码，若存在则更新邮箱对应的验证码
        # 可以使用redis存储验证码
        # captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()  # 通过邮箱查询对应的邮箱验证码
        # captcha_model = redis_store.get("valid_code:{}".format(email))
        # 如果存在验证码
        # if captcha_model:
        #     captcha_model.captcha = captcha
        #     captcha_model.creat_time = datetime.now()
        #     db.session.commit()
        # else:
        #     captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
        # db.session.add(captcha_model)
        # db.session.commit()
        # 将验证码保存到redis中，第一个参数是key(邮箱)，第二个参数是value（验证码），第三个参数表示120秒后过期
        # redis_store.set("valid_code:{}".format(email), captcha, 120)
        redis_store.set("valid_code:{}".format(email), captcha)
        return jsonify({"code": 200, "message": "验证码发送成功"})
    else:
        # 400 为客户端错误
        return jsonify({"code": 400, "message": "请先传递邮箱"})


# 更改密码
@bp.route("/repassword", methods=["GET", "POST"])
def repassword():
    if request.method == "GET":
        return render_template("repassword.html")

    else:
        form = RepasswordForm(request.form)
        user = g.user
        password0 = request.form.get('password0')
        password1 = form.password1.data
        password2 = request.form.get('password2')
        # 输入的原密码错误
        if not check_password_hash(user.password, password0):
            flash("密码错误")
            return redirect(url_for("user.repassword"))
        # 输入的原密码正确，判断更改后的密码是否符合要求
        else:
            if form.validate():
                if password1 == password2:
                    g.user.password = generate_password_hash(password1)
                    # 清除session中的数据
                    try:
                        session.clear()
                        db.session.commit()
                        return redirect(url_for('user.login'))
                    except:
                        db.session.rollback()
                        return redirect(url_for("user.repassword"))
                else:
                    flash("更改后的两次密码不一致")
                    return redirect(url_for("user.repassword"))
            else:
                flash("密码格式错误：至少6位，最多20位")
                return redirect(url_for("user.repassword"))


# 用户信息视图
@bp.route('/user_message', methods=['GET', 'POST'])
@login_required
def user_message():
    # 获取用户名
    user = g.user
    username = user.username
    # 获取用户对象
    user = UserModel.query.filter_by(username=username).first()
    # # 将用户对象装换成用户字典
    # user_dict = user.to_dict()

    # 根据请求方式不同做出不同的响应
    if request.method == 'GET':
        # return render_template('test/user_message.html', user=user_dict)
        return render_template('user_message.html')
    # 获取用户输入并更新数据库
    else:
        form = MessageForm(request.form)
        username = form.username.data
        sex = request.form.get('sex')
        avatar = request.files.get('avatar')

        # 如果上传了头像才保存和更新数据库的头像信息
        if avatar:
            # 设置头像存储路径
            absolute_avatar_path = current_app.static_folder + '\images\{}.png'.format(username)
            # 保存图片
            with open(absolute_avatar_path, 'wb+') as f:
                f.write(avatar.read())
                f.close()
            user.avatar_url = absolute_avatar_path

        # 更新用户信息
        user.username = username
        user.sex = sex
        try:
            db.session.commit()
        except:
            db.session.rollback()

        # 更新session的name
        session["name"] = username

        # # 将更新后的对象装换成字典
        # user_dict = user.to_dict()
        # 返回更新结果
        return redirect(url_for('user.user_message'))


# 返回用户头像
@bp.route('/user_avatar', methods=["GET"])
def user_avatar():
    username = session.get('name')

    # 获取用户
    user = UserModel.query.filter_by(username=username).first()

    # 获取当前用户的头像
    avatar_url = user.avatar_url
    print(avatar_url)
    # 如果用户头像不存在，则返回默认头像
    # current_app.send_static_file("文件路径") 能返回静态文件夹里面的文件
    if not avatar_url:
        if user.sex == '男':
            print(current_app.send_static_file('static/images/nstx.png'))
            return current_app.send_static_file('static/images/nstx.png')
        if user.sex == '女':
            print(current_app.send_static_file('static/images/vstx.png'))
            return current_app.send_static_file('static/images/vstx.png')
    else:
        # 头像存在，则正常返回
        print(current_app.send_static_file('static/images/{}.png'.format(username)))
        return current_app.send_static_file('static/images/{}.png'.format(username))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap@4.3.1.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/init.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container"> {# 将该div中包含的组件居中显示 #}
        <img class="" src="{{ url_for('static',filename='images/logo.jpg') }}" alt="" style="margin-right: 6px">
        <a class="navbar-brand" href="#">知了问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"> {# active：活跃/常亮 #}
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
                        <input class="form-control mr-sm-0" style="width:240px" type="search"
                               placeholder="在标题和内容中查找关键字" aria-label="Search"
                               name="key">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">查找</button>
                    </form>
                </li>
            </ul>
            {# mr-auto：自动居中 #}
            <ul class="navbar-nav">
                {% if user %}
                <img class="tx" src="{{ url_for('static',filename='images/nstx.png') }}" alt="" style="margin-right: 6px" width="40" height="40">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.user_message') }}" >{{ user.username }}</a>
                </li>
                <!--                    <li class="nav-item">-->
                <!--                        <span class="nav-link">{{ user.username }}</span>-->
                <!--                    </li>-->
                <!--                    <li class="nav-item">-->
                <!--                        <a class="nav-link" href="{{ url_for('user.repassword') }}">修改密码</a>-->
                <!--                    </li>-->
                <!--                    <li class="nav-item">-->
                <!--                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>-->
                <!--                    </li>-->


                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">登录 </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }}{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}


{% block body %}
    <div class="row" style="margin-top: 20px">
        <div class="col"></div>
        <div class="col-8" style="background-color: #fff; padding: 20px;">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>作者：{{ question.author.username }}</span>
                <span>时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">{{ question.content }}</p>
            <hr>

            <h4 class="comment-group-title">评论({{ question.answers|length }})：</h4>
            <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
                <input type="hidden" name="question_id" value="{{ question.id }}">
                <div class="form-group">
<!--                    <input type="text" placeholder="请填写评论" name="content" class="form-control">-->
                    <textarea name="content" class="form-control" rows="5" placeholder="请输入评论"></textarea>
                </div>

                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}

                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">评论</button>
                </div>
            </form>
            <ul class="comment-group">
                {% if not question.answers %}
                    <li>
                        <p class="no-content">暂无评论，快去说出你的想法吧</p>
                    </li>

                {% else %}

                    {% for answer in question.answers %}
                        <li>
                            <div class="user-info">
                                <img class="avatar" src="{{ url_for('static',filename='images/tx.jpg') }}" alt="">
                                <span class="username">{{ answer.author.username }}</span>
                                <span class="create-time">{{ answer.create_time }}</span>
                            </div>
                            <p class="comment-content">{{ answer.content }}</p>
                        </li>
                    {% endfor %}

                {% endif %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{# 继承基础模板 #}
{% extends "base.html" %}

{% block title %}知了问答-首页{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8">
            <ul class="question-ul">
                {% if not questions %}
                    <p class="no-question">暂无内容，快去发布你的问题吧</p>

                {% else %}

                    {% for question in questions %}
                        <li>
                            <div class="side-question">
                                <img class="side-question-avatar" src="{{ url_for('static',filename='images/tx.jpg') }}" alt=""> {# 图片，头像 #}
                            </div>
                            <div>
                                <div class="question-main">
                                    <div class="question-title"><a href="{{ url_for('qa.question_detail',question_id=question.id) }}">{{ question.title }}</a></div>
                                    <div class="question-content">{{ question.content }}</div>
                                    <div class="question-detail">
                                        <span class="question-author">{{ question.author.username }}</span>
                                        <span class="question-time">{{ question.create_time }}</span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}

                {% endif %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/login.html
{# 继承基础模板 #}
{% extends "base.html" %}
{% block title %}知了问答-登录{% endblock %}
{% block head %}
<script src="{{ url_for('static',filename='jquery/jquery.3.6.0.min.js') }}"></script>
{% endblock %}
{% block body %}
<div class="row mt-4"> {# 使用栅格系统，设置 列，只在中间一列插入数据 #}
    <div class="col"></div>
    <form action="{{ url_for('user.login') }}" method='POST' style="width:360px">
        <div class="form-group">
            <label for="exampleInputEmail1">邮箱</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
            <small id="emailHelp" class="form-text text-muted">我们不会把您的邮箱用于其他地方.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>

        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}


        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">记住我</label>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">登录</button>
        </div>
    </form>
    <div class="col"></div>
</div>
{% endblock %}

templates/public_question.html
{% extends  "base.html" %}

{% block title %}发布问答{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px">  {# 顶部距离 #}
        <div class="col"></div>
        <div class="col-10">
            <h1 style="text-align: center">发布问答</h1>
            <form action="{{ url_for('qa.public_question') }}" method="post">
                <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="请输入标题">
                </div>
                <div class="form-group">
                    <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                </div>

                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}

                <div class="from-group" style="text-align: right">
                    <button class="btn btn-primary">发布</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/register.html
{# 继承基础模板 #}
{% extends "base.html" %}
{% block title %}知了问答-注册{% endblock %}
{% block head %}
<script src="{{ url_for('static',filename='jquery/jquery.3.6.0.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}
{% block body %}
<div class="row mt-4"> {# 使用栅格系统，设置 列，只在中间一列插入数据 #}
    <div class="col"></div>
    <form method="POST" action="{{ url_for('user.register') }}" style="width:360px">

        <div class="form-group">
            <label for="exampleInputEmail1">邮箱</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
            <small id="emailHelp" class="form-text text-muted">我们不会把您的邮箱用于其他地方.</small>
        </div>


        <div class="form-group">
            <label for="exampleInputEmail1">验证码</label>

            <div class="input-group">
                <input type="text" class="form-control" name="captcha">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-ptn">点击获取验证码！</button>
                </div>
            </div>
            <small id="captchaHelp" class="form-text text-muted">验证码区分大小写.</small>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">用户名</label>
            <input type="text" class="form-control" id="exampleInputUserName" name="username">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
            <small id="passwordaHelp" class="form-text text-muted">密码长度6至20位长度.</small>
        </div>


        <div class="form-group">
            <label for="exampleInputPassword1">确认密码</label>
            <input type="password" class="form-control" id="exampleInputPassword2" name="password_confirm">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">性别：</label>
            <input type="radio" name="sex" checked value="男">男
            <input type="radio" name="sex" value="女">女
        </div>

        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{message}}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary btn-block">注册</button>
        {# btn-block 设置按钮宽度为：于上等宽 #}
    </form>
    <div class="col"></div>
</div>
{% endblock %}

templates/repassword.html
{% extends "base.html" %}
{% block title %}知了问答-更改密码{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='jquery/jquery.3.6.0.min.js') }}"></script>
{% endblock %}
{% block body %}
    <div class="row mt-4">  {# 使用栅格系统，设置 列，只在中间一列插入数据 #}
        <div class="col"></div>
        <form action="{{ url_for('user.repassword') }}" method='POST' style="width:360px">
            <div class="form-group">
                <label for="exampleInputPassword1">原密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password0">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">新密码</label>
                <input type="password" class="form-control" id="exampleInputPassword2" name="password1">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">确认密码</label>
                <input type="password" class="form-control" id="exampleInputPassword3" name="password2">
            </div>

           {% for message in get_flashed_messages() %}
               <div class="form-group">
                <div class="text-danger">{{ message }}</div>
               </div>
           {% endfor %}

            <div class="form-group">
                <button type="submit" class="btn btn-primary">确认</button>
            </div>
        </form>
        <div class="col"></div>
    </div>
{% endblock %}

templates/user_message.html
{% extends "base.html" %}
{% block title %}知了问答-用户信息{% endblock %}
{% block head %}
<script src="{{ url_for('static',filename='jquery/jquery.3.6.0.min.js') }}"></script>
<!--<script src="{{ url_for('static',filename='js/avatar.js') }}"></script>-->
<link rel="stylesheet" href="{{ url_for('static', filename='CSS/message.css') }}">
{% endblock %}

{% block body %}
<!--<img src="{{ url_for('static',filename='images/xxxx.png') }}" alt="" id="avatar_img" style="margin-right: 6px">-->
<img src="{{ url_for('static',filename='images/xxxx.png') }}" alt="" id="avatar_img" style="margin-right: 6px">
<div class="row mt-4"> {# 使用栅格系统，设置行，只在中间一列插入数据 #}
    <div class="col-4"></div>
    {# 使用栅格系统，设置列，只在中间一列插入数据 #}
    <form action="{{ url_for('user.user_message') }}" enctype="multipart/form-data" method="post">
        <div class="form-group">
            <label> 用户头像：</label>
            <input type="file" name="avatar" id="avatar"><br>

            <label> 账号：</label>
            <a type="text" name="email">{{user.email}}</a><br>

            <label> 用户名：</label>
            <input type="text" value="{{user.username}}" name="username"><br>

            <label> 注册时间：</label>
            <a type="text" name="join_time">{{user.join_time}}</a><br>

            <label> 性别：</label>
            {% if user.sex== '男' %}
            <input type="radio" value="男" checked name="sex">男
            <input type="radio" value="女" name="sex">女
            {% else %}
            <input type="radio" value="男" name="sex">男
            <input type="radio" value="女" checked name="sex">女
            {% endif %}
            <br>
            <!--            <input type="submit" value="提交">-->
            <div class="from-group" style="text-align: right">
                <button class="btn btn-primary" type="submit">提交</button>
            </div>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.repassword') }}">修改密码</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                </li>
            </ul>

            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endfor %}

        </div>
    </form>
</div>
{# display:block; 将行内标签转换为块级元素  text-align:right; 文字向右对齐  #}
<!--<a href="/" style="font-size:20px;display:block;text-align:right;">返回首页</a>-->
<script>
    // 头像预览
    $(function () {
    $('#avatar').change(function () {
        // 1.创建文件阅读器对象
        let avatar_img = new FileReader()
        // 2.获取用户上传的文件对象
        let up_avatar = $(this)[0].files[0];
        // 3.将文件对象交给阅读器对象解析
        avatar_img.readAsDataURL(up_avatar)
        // 4.等待文件阅读器加载完毕，利用文件阅读器将文件展示到前端页面，修改src属性，
        // avatar_img.result 获取图像路径
        avatar_img.onload = function () {
            $('#avatar_img').attr('src', avatar_img.result)
        }
    })
})
</script>
{% endblock %}

templates/warn.html
{% extends "base.html" %}
 
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='CSS/warn.css') }}">
    <script src="{{ url_for('static',filename='js/timer.js') }}"></script>
{% endblock %}
 
{% block page_name %}提示{% endblock %}
 
{% block body %}
<div class="informs" style="margin-top:30px">
    <h4 style="margin:10px 10px" >提示信息</h4>
    <p>
        <span class="key-message" style="margin-left:10px">未找到相关结果。</span>
        <span id="timer">5</span>秒后将自动跳转回首页。
    </p>
    <div class="jump-button">
        <button type="submit" class="btn btn-primary pull-right" style="float:right" onclick="location='{{ url_for('qa.index') }}'">立即跳转</button>
    </div>
</div>
<script type="text/javascript">timetojump(5,"{{ url_for('qa.index') }}");</script>
{% endblock %}